### ISSUE TITLE
Noticias de la UNAM

### ISSUE THREAD

**Issue by IsaTreAgu** [IsaTreAgu/Tesis#3]
Hola Miguel, me escribieron del posgrado en la UNAM diciéndome que tal vez aún hay posibilidades de terminar con el trámite de doctorado, para ello es necesario escribirle una carta al comité académico (la anexo), ¿qué te parece?

Tu autorización para este trámite me parece muy importante, sobre todo si has leído ya, parte de lo que he escrito, porque pienso obtener de ahí el artículo y la tesis, que son los documentos que me hacen falta.

Te mando saludos y platicamos pronto.
Saludos
[solicitud-de-reincoporacionUNAM.docx](https://github.com/IsaTreAgu/Tesis/files/11254071/solicitud-de-reincoporacionUNAM.docx)

**Comment by equihuam** [comment]
Excelente noticia. Hay que darle!!!!
